using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.RightsManagement;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Controls;

namespace ChampRecommender.Models
{
    public class Champion
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        public List<string>? Lanes { get; set; }

    }

    static class ChampionList
    {
        public static List<string> names = new List<string>()
        {
            "Aatrox",
            "Ahri",
            "Akali",
            "Akshan",
            "Alistar",
            "Amumu",
            "Anivia",
            "Annie",
            "Aphelios",
            "Ashe",
            "Aurelion Sol",
            "Azir",
            "Bard",
            "Bel'Veth",
            "Blitzcrank",
            "Brand",
            "Braum",
            "Caitlyn",
            "Camille",
            "Cassiopeia",
            "Cho'Gath",
            "Corki",
            "Darius",
            "Diana",
            "Draven",
            "Dr. Mundo",
            "Ekko",
            "Elise",
            "Evelynn",
            "Ezreal",
            "Fiddlesticks",
            "Fiora",
            "Fizz",
            "Galio",
            "Gangplank",
            "Garen",
            "Gnar",
            "Gragas",
            "Graves",
            "Gwen",
            "Hecarim",
            "Heimerdinger",
            "Illaoi",
            "Irelia",
            "Ivern",
            "Janna",
            "Jarvan IV",
            "Jax",
            "Jayce",
            "Jhin",
            "Jinx",
            "Kai'Sa",
            "Kalista",
            "Karma",
            "Karthus",
            "Kassadin",
            "Katarina",
            "Kayle",
            "Kayn",
            "Kennen",
            "Kha'Zix",
            "Kindred",
            "Kled",
            "Kog'Maw",
            "K'Sante",
            "LeBlanc",
            "Lee Sin",
            "Leona",
            "Lillia",
            "Lissandra",
            "Lucian",
            "Lulu",
            "Lux",
            "Malphite",
            "Malzahar",
            "Maokai",
            "Master Yi",
            "Milio",
            "Miss Fortune",
            "Wukong",
            "Mordekaiser",
            "Morgana",
            "Nami",
            "Nasus",
            "Nautilus",
            "Neeko",
            "Nidalee",
            "Nilah",
            "Nocturne",
            "Nunu & Willump",
            "Olaf",
            "Orianna",
            "Ornn",
            "Pantheon",
            "Poppy",
            "Pyke",
            "Qiyana",
            "Quinn",
            "Rakan",
            "Rammus",
            "Rek'Sai",
            "Rell",
            "Renata Glasc",
            "Renekton",
            "Rengar",
            "Riven",
            "Rumble",
            "Ryze",
            "Samira",
            "Sejuani",
            "Senna",
            "Seraphine",
            "Sett",
            "Shaco",
            "Shen",
            "Shyvana",
            "Singed",
            "Sion",
            "Sivir",
            "Skarner",
            "Sona",
            "Soraka",
            "Swain",
            "Sylas",
            "Syndra",
            "Tahm Kench",
            "Taliyah",
            "Talon",
            "Taric",
            "Teemo",
            "Thresh",
            "Tristana",
            "Trundle",
            "Tryndamere",
            "Twisted Fate",
            "Twitch",
            "Udyr",
            "Urgot",
            "Varus",
            "Vayne",
            "Veigar",
            "Vel'Koz",
            "Vex",
            "Vi",
            "Viego",
            "Viktor",
            "Vladimir",
            "Volibear",
            "Warwick",
            "Xayah",
            "Xerath",
            "Xin Zhao",
            "Yasuo",
            "Yone",
            "Yorick",
            "Yuumi",
            "Zac",
            "Zed",
            "Zeri",
            "Ziggs",
            "Zilean",
            "Zoe",
            "Zyra"
        };
        public static List<int> ids = new List<int>()
        {
            266,
            103,
            84,
            166,
            12,
            32,
            34,
            1,
            523,
            22,
            136,
            268,
            432,
            200,
            53,
            63,
            201,
            51,
            164,
            69,
            31,
            42,
            122,
            131,
            119,
            36,
            245,
            60,
            28,
            81,
            9,
            114,
            105,
            3,
            41,
            86,
            150,
            79,
            104,
            887,
            120,
            74,
            420,
            39,
            427,
            40,
            59,
            24,
            126,
            202,
            222,
            145,
            429,
            43,
            30,
            38,
            55,
            10,
            141,
            85,
            121,
            203,
            240,
            96,
            897,
            7,
            64,
            89,
            876,
            127,
            236,
            117,
            99,
            54,
            90,
            57,
            11,
            902,
            21,
            62,
            82,
            25,
            267,
            75,
            111,
            518,
            76,
            895,
            56,
            20,
            2,
            61,
            516,
            80,
            78,
            555,
            246,
            133,
            497,
            33,
            421,
            526,
            888,
            58,
            107,
            92,
            68,
            13,
            360,
            113,
            235,
            147,
            875,
            35,
            98,
            102,
            27,
            14,
            15,
            72,
            37,
            16,
            50,
            517,
            134,
            223,
            163,
            91,
            44,
            17,
            412,
            18,
            48,
            23,
            4,
            29,
            77,
            6,
            110,
            67,
            45,
            161,
            711,
            254,
            234,
            112,
            8,
            106,
            19,
            498,
            101,
            5,
            157,
            777,
            83,
            350,
            154,
            238,
            221,
            115,
            26,
            142,
            143
        };
        public static List<List<string>> lanes = new List<List<string>>()
        {
            new List<string>(){"TOP"},
            new List<string>(){"MID"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"JUNGLE", "SUPPORT"},
            new List<string>(){"MID"},
            new List<string>(){"MID", "SUPPORT"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"BOTTOM", "SUPPORT"},
            new List<string>(){"MID"},
            new List<string>(){"MID"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"TOP"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"MID"},
            new List<string>(){"TOP"},
            new List<string>(){"JUNGLE", "MID"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"TOP"},
            new List<string>(){"JUNGLE", "MID"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"JUNGLE", "SUPPORT"},
            new List<string>(){"TOP"},
            new List<string>(){"MID"},
            new List<string>(){"MID"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP"},
            new List<string>(){"TOP", "JUNGLE", "MID"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"TOP"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"JUNGLE", "BOTTOM"},
            new List<string>(){"MID"},
            new List<string>(){"MID"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"MID", "SUPPORT"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"MID"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"MID", "SUPPORT"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"MID"},
            new List<string>(){"TOP", "JUNGLE", "SUPPORT"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"BOTTOM", "SUPPORT"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"TOP"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"TOP"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"MID"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP"},
            new List<string>(){"MID"},
            new List<string>(){"TOP"},
            new List<string>(){"TOP", "MID", "SUPPORT"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"MID"},
            new List<string>(){"TOP"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"TOP"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"MID"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"BOTTOM", "SUPPORT"},
            new List<string>(){"TOP"},
            new List<string>(){"JUNGLE", "SUPPORT"},
            new List<string>(){"TOP"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"MID", "SUPPORT"},
            new List<string>(){"TOP", "JUNGLE", "MID"},
            new List<string>(){"MID"},
            new List<string>(){"TOP", "SUPPORT"},
            new List<string>(){"MID"},
            new List<string>(){"JUNGLE", "MID"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"TOP"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"MID", "BOTTOM"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP"},
            new List<string>(){"MID"},
            new List<string>(){"BOTTOM", "SUPPORT"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"TOP"},
            new List<string>(){"MID", "BOTTOM"},
            new List<string>(){"TOP", "BOTTOM"},
            new List<string>(){"MID", "BOTTOM"},
            new List<string>(){"MID", "SUPPORT"},
            new List<string>(){"MID"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"MID"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"TOP", "JUNGLE"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"MID", "SUPPORT"},
            new List<string>(){"JUNGLE"},
            new List<string>(){"TOP", "MID", "BOTTOM"},
            new List<string>(){"TOP", "MID"},
            new List<string>(){"TOP"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"TOP", "JUNGLE", "SUPPORT"},
            new List<string>(){"JUNGLE", "MID"},
            new List<string>(){"BOTTOM"},
            new List<string>(){"MID", "BOTTOM"},
            new List<string>(){"SUPPORT"},
            new List<string>(){"MID"},
            new List<string>(){"SUPPORT"}
        };
    }
}
